name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Run on EC2
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hari1479/tindog
      TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            IMAGE_NAME=hari1479/tindog
            TAG=latest

            docker rm -f tindog-container || true
            docker pull $IMAGE_NAME:$TAG
            docker run -d --name tindog-container -p 8081:80 $IMAGE_NAME:$TAG
